/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace DashcamNet.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class @Event : TBase
  {
    private long _sequenceNo;
    private string _route;

    public string NameSpace { get; set; }

    public string Name { get; set; }

    public long Time { get; set; }

    public Dictionary<string, string> Attributes { get; set; }

    public long SequenceNo
    {
      get
      {
        return _sequenceNo;
      }
      set
      {
        __isset.sequenceNo = true;
        this._sequenceNo = value;
      }
    }

    public string Route
    {
      get
      {
        return _route;
      }
      set
      {
        __isset.route = true;
        this._route = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sequenceNo;
      public bool route;
    }

    public @Event() {
    }

    public Event(string nameSpace, string name, long time, Dictionary<string, string> attributes) : this() {
      this.NameSpace = nameSpace;
      this.Name = name;
      this.Time = time;
      this.Attributes = attributes;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_nameSpace = false;
      bool isset_name = false;
      bool isset_time = false;
      bool isset_attributes = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              NameSpace = iprot.ReadString();
              isset_nameSpace = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Name = iprot.ReadString();
              isset_name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              Time = iprot.ReadI64();
              isset_time = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Map) {
              {
                Attributes = new Dictionary<string, string>();
                TMap _map18 = iprot.ReadMapBegin();
                for( int _i19 = 0; _i19 < _map18.Count; ++_i19)
                {
                  string _key20;
                  string _val21;
                  _key20 = iprot.ReadString();
                  _val21 = iprot.ReadString();
                  Attributes[_key20] = _val21;
                }
                iprot.ReadMapEnd();
              }
              isset_attributes = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              SequenceNo = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              Route = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_nameSpace)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_name)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_time)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_attributes)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Event");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "nameSpace";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(NameSpace);
      oprot.WriteFieldEnd();
      field.Name = "name";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Name);
      oprot.WriteFieldEnd();
      field.Name = "time";
      field.Type = TType.I64;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Time);
      oprot.WriteFieldEnd();
      field.Name = "attributes";
      field.Type = TType.Map;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.String, Attributes.Count));
        foreach (string _iter22 in Attributes.Keys)
        {
          oprot.WriteString(_iter22);
          oprot.WriteString(Attributes[_iter22]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
      if (__isset.sequenceNo) {
        field.Name = "sequenceNo";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SequenceNo);
        oprot.WriteFieldEnd();
      }
      if (Route != null && __isset.route) {
        field.Name = "route";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Route);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Event(");
      __sb.Append(", NameSpace: ");
      __sb.Append(NameSpace);
      __sb.Append(", Name: ");
      __sb.Append(Name);
      __sb.Append(", Time: ");
      __sb.Append(Time);
      __sb.Append(", Attributes: ");
      __sb.Append(Attributes);
      if (__isset.sequenceNo) {
        __sb.Append(", SequenceNo: ");
        __sb.Append(SequenceNo);
      }
      if (Route != null && __isset.route) {
        __sb.Append(", Route: ");
        __sb.Append(Route);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
