/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DashcamNet.Thrift
{
  public enum LogType
  {
    OTHER = 0,
    APP = 1,
    URL = 2,
    WEB_SERVICE = 3,
    SQL = 4,
    MEMCACHED = 5,
  }
}
