/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DashcamNet.Thrift
{
  public enum MetricValueType
  {
    TYPE_FLOAT = 0,
    TYPE_LONG = 1,
  }
}
