/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DashcamNet.Thrift
{
  public enum ResultCode
  {
    SUCCESS = 0,
    FAILURE = 1,
    TRY_LATER = 2,
  }
}
