/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DashcamNet.Thrift
{
  public enum SpanType
  {
    OTHER = 0,
    URL = 1,
    WEB_SERVICE = 2,
    SQL = 3,
    MEMCACHED = 4,
  }
}
